### PR TITLE
run foreman-ansible-modules tests

### PR DESCRIPTION
**Pull request by evgeni**
this will ensure we don't break our biggest consumer

### CODE REVIEW

**Comment by evgeni** [comment]
tests are failing because this exposes an actual "bug" we introduced :)

**Comment by mdellweg** [comment]
Do we want this to add to the test coverage?

**Comment by evgeni** [comment]
how?

**Comment by mdellweg** [comment]
OK, that would be more complicated. We needed to load the coverage module in the vcr_python_wrapper.

**Pull request merged**
